//fonts + styling
import { Inter } from "next/font/google";
import "./globals.css";

import { Providers } from "./lib/providers";

const inter = Inter({ subsets: ["latin"] });

import NavBar from "./ui/navBar";
import Footer from "./ui/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NavBar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
